# Generated by Django 5.2.7 on 2025-12-17 16:58

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth','Group')
    Permission = apps.get_model('auth','Permission')
    ContentType = apps.get_model('contenttypes','ContentType')

    #Buscar ContentType de Tarefa
    try:
        tarefa_ct = ContentType.objects.get(app_label='core',model='tarefa')
    except ContentType.DoesNotExist:
        return
        
    #Criar Grupos
    grupo_comum,_ = Group.objects.get_or_create(name='Comum')
    grupo_gerente,_ = Group.objects.get_or_create(name='Gerente')

    #Permissões
    perms_comum = Permission.objects.filter(
        content_type=tarefa_ct,
        codename_in=['add_tarefa','view_tarefa','change_tarefa']
    )

    perms_gerente = Permission.objects.filter(
        content_type=tarefa_ct,
    )

    grupo_comum.permissions.set(perms_comum)
    grupo_gerente.permissions.set(perms_gerente)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]

    