# Generated by Django 5.2.7 on 2025-12-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tarefa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='deletada',
            field=models.BooleanField(default=False, verbose_name='Deletada'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Conclusão'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
    ]
